In [3]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])

print(a * b)
print(a @ b)

a = np.matrix([[1, 2],
              [3, 4]])
b = np.matrix([[5, 6],
              [7, 8]])

print(a * b)
print(a @ b)

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [7]:
import numpy as np

#doc1 = [2, 1, 1, 1, 0, 0, 0, 0, 0, 0]
#doc2 = [1, 1, 0, 0, 1, 1, 1, 1, 0, 0]
#doc3 = [1, 1, 0, 0, 1, 1, 1, 1, 1, 1]
#doc4 = [2, 2, 0, 0, 1, 1, 1, 1, 0, 0]
#
#q2 = [2, 2, 0, 0, 0, 2, 0, 0, 0, 0] # I LIKE EGGS I LIKE EGGS
#query = [1, 1, 0, 0, 0, 1, 0, 0, 0, 0]
doc1 = [0,0,1.585,1.585,0,0,0,0,0,0]
doc2 = [0,0,0,0,0.585,0.585,0.585,0.585,0,0]
doc3 = [0,0,0,0,0.585,0.585,0.585,0.585,1.585,1.585]
query = [0,0,0,0,0,0.585,0,0,0,0]

def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

def euclidean_distance(a, b):
    return np.linalg.norm(np.array(a) - np.array(b))

print(cosine_similarity(doc1, query))
print(cosine_similarity(doc2, query))
print(cosine_similarity(doc3, query))

print(euclidean_distance(doc1, query))
print(euclidean_distance(doc2, query))
print(euclidean_distance(doc3, query))


0.0
0.5
0.2313617848170575
2.3166085124595392
1.0132497224277932
2.45990345338999
